blank_issues_enabled: false
contact_links:
  - name: General Questions or Feedback
    url: https://github.com/YOUR_ORG/YOUR_REPO/discussions
    about: Please use GitHub Discussions for general questions or feedback.
